# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='choice',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SOLVED', 'SOLVED'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=40),
        ),
    ]
